// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzqzsvbjpqdjmtkvwsmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cXpzdmJqcHFkam10a3Z3c21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODQ0MjcsImV4cCI6MjA4NTM2MDQyN30.oS-wShgnUDsSqAB1fr90TOLWiHQ7mUWp_A7BKjzj4ew";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});